import { ThemeDefinition } from "./type";

export const BaseTheme: ThemeDefinition = {
    palletete: {
        primary: "#0070f3",
        secondary: "#1db954",
        background: "#ffffff",
        text: "#000000",
        error: "#ff0000",
        warning: "#ffcc00",
        success: "#00ff00",
        info: "#0000ff",
        light: "#f0f0f0",
        dark: "#000000",
        muted: "#6c757d",
        accent: "#ff4081",
        highlight: "#ffeb3b",
        shadow: "#000000",
        border: "#e0e0e0",
        link: "#0070f3",
        linkHover: "#0056b3",
        linkActive: "#0056b3",
        linkVisited: "#6f42c1",
        linkDisabled: "#6c757d",
        linkFocus: "#0056b3",
        linkActiveHover: "#0056b3",
        linkActiveFocus: "#0056b3",
        linkVisitedHover: "#6f42c1",
        linkVisitedFocus: "#6f42c1",
        linkDisabledHover: "#6c757d",
    },
    radius: {
        small: "4px",
        medium: "8px",
        large: "16px",
        circle: "50%",
        pill: "9999px",
        square: "0px",
        rounded: "8px",
    },
    spacing: (factor: number) => `${factor * 8}px`,
    font: {
        family: "'Helvetica Neue', Arial, sans-serif",
        size: {
            small: "12px",
            medium: "14px",
            large: "16px",
            xlarge: "18px",
            xxlarge: "20px",
            xxxlarge: "24px",
            tiny: "10px",
            xsmall: "11px",
        },
    },
  };